// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znpzbphywuragqvqqexp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpucHpicGh5d3VyYWdxdnFxZXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTIzMzEsImV4cCI6MjA2NTQ4ODMzMX0.lPbYz5o6N-BKJrWbQ1MEenOtSdgV2XKufuTEJmS9wQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);